Fix GCC unused result warning in JobAgent sample
This change is to fix a GCC `unused-result` warning when I was building
the JobAgent sample. The return value from the `system` call isn't used.
I am using Ubuntu 19.04 and GCC 8.3.0.

```
aws-iot-device-sdk-cpp/samples/JobsAgent/JobsAgentOperations.cpp: In member function ‘awsiotsdk::ResponseCode awsiotsdk::samples::JobsAgent::UpdateAcceptedCallback(awsiotsdk::util::String, awsiotsdk::util::String, std::shared_ptr<awsiotsdk::mqtt::SubscriptionHandlerContextData>)’:
aws-iot-device-sdk-cpp/samples/JobsAgent/JobsAgentOperations.cpp:639:39: error: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Werror=unused-result]
                                 system(systemCommand.c_str());
                                 ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [tests/unit/CMakeFiles/aws-iot-unit-tests.dir/build.make:63: tests/unit/CMakeFiles/aws-iot-unit-tests.dir/__/__/samples/JobsAgent/JobsAgentOperations.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:244: tests/unit/CMakeFiles/aws-iot-unit-tests.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```